# Generated by Django 3.2.4 on 2021-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('stockId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stockName', models.CharField(max_length=100)),
            ],
        ),
    ]
