# Generated by Django 3.2.4 on 2021-06-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
